Repository erikabusiness/dart_plus_app, pull requests merged in 2024-05, with the labels that each got.

#8 fix: Trocar de nome da classe de films para movies.
  lib/classes/popular_films.dart
  lib/classes/popular_movies.dart
Labels: Sprint 1

#5 Feat: class creation popularSeries
  lib/classes/popular_series.dart
Labels: Sprint 1

#18 feat: definições de estilo
  lib/assets/logo.png
  lib/assets/logo.svg
  lib/styles/colors.dart
  lib/styles/fonts.dart
  pubspec.lock
  pubspec.yaml
Labels: Sprint 1

#21 style: Criação da GridView vertical para a vizualização das mídias.
  lib/main.dart
  lib/wigets/grid_view_vertical.dart
  pubspec.lock
  pubspec.yaml
Labels: Sprint 1, Home page

#16 Consumir metadados pelo Json
  lib/assets/data/popular_data.json
  lib/classes/popular_series.dart
  lib/data/mock/fetch/localdataservice.dart
  lib/data/mock/fetch/seach_result.dart
  lib/main.dart
  lib/wigets/grid_view_vertical.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
Labels: Sprint 1

#22 fix: Corrigir bug no gridView
  lib/wigets/grid_view_vertical.dart
Labels: bug, Home page

#19 criação do título de filmes e séries
  lib/main.dart
  lib/widgets/title_section.dart
Labels: Sprint 1, Home page

#25 fix: Corrigir bug no texto do GridView
  lib/data/mock/fetch/seach_result.dart
  lib/main.dart
  lib/widgets/grid_view_vertical.dart
Labels: bug, Home page

#24 Feito a criação do título "Filmes e Séries Populares".
  lib/widgets/title_section.dart
Labels: Sprint 1, Home page

#26 Definição do tema do APP para Dark.
  lib/main.dart
Labels: Sprint 1, Home page

#27 style: adicionar barra de pesquisa na home page
  lib/main.dart
  lib/widgets/search_bar.dart
Labels: Sprint 1, Home page

#28 style: adicionar logo do app na app bar
  assets/logo.png
  assets/logo.svg
  lib/assets/data/popular_data.json
  lib/main.dart
  pubspec.yaml
Labels: Sprint 1, Home page

#29 Merge Home page to Developer
  assets/logo.png
  assets/logo.svg
  lib/classes/popular_movies.dart
  lib/classes/popular_series.dart
  lib/data/mock/fetch/localdataservice.dart
  lib/data/mock/fetch/seach_result.dart
  lib/data/mock/popularMovies.json
  lib/data/mock/popularTvSeries.json
  lib/data/mock/trending.json
  lib/main.dart
  lib/styles/colors.dart
  lib/styles/fonts.dart
  lib/widgets/grid_view_vertical.dart
  lib/widgets/search_bar.dart
  lib/widgets/title_section.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: Sprint 1

#32 separates the home page from the main file
  lib/main.dart
  lib/view/home_page.dart
  pubspec.yaml
Labels: Sprint 2, Home page

#33 create details page file
  lib/view/details_page.dart
Labels: Sprint 2, Details page

#36 feat: Criar tela 'ver todos' de filmes populares
  lib/view/see_all_popular_movies.dart
Labels: Sprint 2, See all

#34 Refactor: Separar a home page do arquivo main
  lib/main.dart
  lib/view/home_page.dart
  pubspec.yaml
Labels: Home page

#38 feat: Adiciona o list view de filmes e séries populares a 'home-page'
  lib/classes/media.dart
  lib/classes/popular_movies.dart
  lib/classes/popular_series.dart
  lib/view/home_page.dart
  lib/widgets/clickable_text.dart
  lib/widgets/grid_view_vertical.dart
  lib/widgets/list_view_horizontal.dart
  lib/widgets/media_card.dart
  pubspec.yaml
Labels: Sprint 2, Home page

#46 feat: adicionar logica de pesquisa e filtragem por título na searchbar
  lib/classes/media.dart
  lib/classes/popular_movies.dart
  lib/classes/popular_series.dart
  lib/data/mock/fetch/localdataservice.dart
  lib/data/mock/fetch/seach_result.dart
  lib/main.dart
  lib/view/home_page.dart
  lib/view/see_all_popular_movies.dart
  lib/view/see_all_popular_series.dart
  lib/widgets/clickable_text.dart
  lib/widgets/grid_view_vertical.dart
  lib/widgets/list_view_horizontal.dart
  lib/widgets/media_card.dart
  lib/widgets/search_bar.dart
  pubspec.yaml
Labels: Sprint 2, Home page

#47 feat: adiciona a feature home page na developer
  lib/view/home_page.dart
  lib/widgets/list_view_horizontal.dart
  lib/widgets/search_bar.dart
Labels: Sprint 2, Home page

#45 Feat: adicionando barra de navegação
  lib/view/home_page.dart
  lib/widgets/navigation_bar.dart
Labels: Sprint 2

#48 feat: adiciona a feature details page na developer
  lib/classes/media.dart
  lib/data/routes.dart
  lib/main.dart
  lib/view/details_page.dart
  lib/view/home_page.dart
  lib/view/see_all_popular_movies.dart
  lib/view/see_all_popular_series.dart
  lib/widgets/caroseul.dart
  lib/widgets/clickable_text.dart
  lib/widgets/grid_view_vertical.dart
  lib/widgets/list_view_horizontal.dart
  lib/widgets/media_card.dart
  lib/widgets/media_trailer.dart
  lib/widgets/navigation_bar.dart
  lib/widgets/story_line.dart
  lib/widgets/title_section.dart
  pubspec.lock
  pubspec.yaml
Labels: Sprint 2, Details page

#52 Gerenciamento de Estados
  .vscode/settings.json
  README.md
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  assets/integrantes/capa_modulo_5.png
  ios/Podfile
  ios/Runner/Info.plist
  lib/data/mock/fetch/localdataservice.dart
  lib/data/mock/fetch/seach_result.dart
  lib/main.dart
  lib/models/media.dart
  lib/models/popular_movies.dart
  lib/models/popular_series.dart
  lib/movies/bloc/popular_movies/popular_movies_bloc.dart
  lib/movies/bloc/popular_movies/popular_movies_event.dart
  lib/movies/bloc/popular_movies/popular_movies_state.dart
  lib/movies/bloc/top_rated_movies/top_rated_movies_bloc.dart
  lib/movies/bloc/top_rated_movies/top_rated_movies_event.dart
  lib/movies/bloc/top_rated_movies/top_rated_movies_state.dart
  lib/movies/bloc/videos_popular_movie/videos_popular_movie_bloc.dart
  lib/movies/bloc/videos_popular_movie/videos_popular_movie_event.dart
  lib/movies/bloc/videos_popular_movie/videos_popular_movie_state.dart
  lib/movies/movie_repository.dart
  lib/routes/api_conections.dart
  lib/routes/routes.dart
  lib/series/bloc/popular_series/popular_series_bloc.dart
  lib/series/bloc/popular_series/popular_series_event.dart
  lib/series/bloc/popular_series/popular_series_state.dart
  lib/series/series_repository.dart
  lib/services/voice_command_service.dart
  lib/styles/colors.dart
  lib/utils/utils_functions.dart
  lib/view/details_page.dart
  lib/view/home_page.dart
  lib/view/see_all_page.dart
  lib/view/see_all_popular_movies.dart
  lib/view/see_all_popular_series.dart
  lib/widgets/caroseul.dart
  lib/widgets/clickable_text.dart
  lib/widgets/grid_view_vertical.dart
  lib/widgets/list_view_horizontal.dart
  lib/widgets/media_card.dart
  lib/widgets/media_trailer.dart
  lib/widgets/navigation_bar.dart
  lib/widgets/search_bar.dart
  lib/widgets/story_line.dart
  lib/widgets/title_section.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile
  pubspec.lock
  pubspec.yaml
Labels: Sprint 1, Módulo 5
